17:39:26  02.03.2021      Функция записи события в журнал   :  (1045, "Access denied for user 'syrnikov'@'localhost' (using password: NO)"). Ошибка в S:\venvGrunt\lib\site-packages\pymysql\err.py строка: 109.
17:35:11  02.03.2021      Функция записи события в журнал   :  (1045, "Access denied for user 'syrnikov'@'localhost' (using password: NO)"). Ошибка в S:\venvGrunt\lib\site-packages\pymysql\err.py строка: 109.

17:24:40  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:40  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:40  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:40  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:40  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:40  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:39  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:39  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:39  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:39  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:39  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:39  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:39  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:38  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:38  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:38  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:38  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:38  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:38  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:38  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:38  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:37  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:37  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:37  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:37  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:37  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:37  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:37  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:37  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:36  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:36  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:36  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:36  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:36  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:36  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:36  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:36  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:35  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:35  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:35  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:35  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:35  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:35  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:35  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:35  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:35  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:34  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:34  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:34  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:34  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:34  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:34  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:34  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:34  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:33  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:33  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:33  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:33  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:33  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:33  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:33  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:33  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:32  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:32  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:32  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:32  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:32  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:32  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:32  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:32  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:31  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:31  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:31  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:31  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:31  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:31  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:31  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:31  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:31  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:30  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:30  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:30  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:30  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:30  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:30  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:30  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:30  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:29  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:29  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:29  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:29  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:29  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:29  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:29  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:29  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:28  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:28  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:28  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:28  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:28  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:28  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:28  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:28  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:27  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:27  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:27  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:27  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:27  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:27  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:27  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:27  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:27  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:26  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:26  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:26  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:26  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:26  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:26  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:26  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:26  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:25  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:25  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:25  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:25  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:25  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:25  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:25  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:25  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:24  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:24  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:24  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:24  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:24  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:24  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:24  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:24  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Поток обновления панели журнала ТС   :  module 'pymysql.connections' has no attribute 'cursor'. Ошибка в s:\Grunt\Grunt\PanelJournalTS.py строка: 4444.

17:24:23  02.03.2021      Функция подключения к БД панель журнала ТС   :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Функция подключения к БД панель журнала ТС   :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Функция подключения к БД панель журнала ТС   :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Функция подключения к БД панель журнала ТС   :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Функция подключения к БД панель журнала ТС   :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:23  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:22  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:21  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:21  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:21  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:21  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:21  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:21  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:21  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:21  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:20  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:20  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:20  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:20  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:20  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:20  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:20  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:20  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:19  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:19  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:19  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:19  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:19  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:19  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:19  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:19  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:19  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:18  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:18  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:18  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:18  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:18  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:18  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:18  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:18  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:17  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:17  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:17  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:17  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:17  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:17  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:17  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:17  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:16  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:16  02.03.2021      Функция обновления таблицы главного окна    :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:16  02.03.2021      Поток обновления панели журнала ТС   :  module 'pymysql.connections' has no attribute 'cursor'. Ошибка в s:\Grunt\Grunt\PanelJournalTS.py строка: 4444.

17:24:16  02.03.2021      Функция подключения к БД панель журнала ТС   :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:16  02.03.2021      Функция подключения к БД панель журнала ТС   :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:16  02.03.2021      Функция подключения к БД панель журнала ТС   :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.

17:24:16  02.03.2021      Функция подключения к БД панель журнала ТС   :  cryptography is required for sha256_password or caching_sha2_password. Ошибка в S:\venvGrunt\lib\site-packages\pymysql\_auth.py строка: 142.


